export const GET_REQUEST_BRAND='GET_REQUEST_BRAND'
export const GET_SUCCESS_BRAND='GET_SUCCESS_BRAND'
export const GET_FAIL_BRAND='GET_FAIL_BRAND'

export const CREATE_REQUEST_BRAND='CREATE_REQUEST_BRAND'
export const CREATE_SUCCESS_BRAND='CREATE_SUCCESS_BRAND'
export const CREATE_FAIL_BRAND='CREATE_FAIL_BRAND'

export const DELETE_REQUEST_BRAND='DELETE_REQUEST_BRAND'
export const DELETE_SUCCESS_BRAND='DELETE_SUCCESS_BRAND'
export const DELETE_FAIL_BRAND='DELETE_FAIL_BRAND'