export const GET_REQUEST_CATEGORY='GET_REQUEST_CATEGORY'
export const GET_SUCCESS_CATEGORY='GET_SUCCESS_CATEGORY'
export const GET_FAIL_CATEGORY='GET_FAIL_CATEGORY'

export const CREATE_REQUEST_CATEGORY='CREATE_REQUEST_CATEGORY'
export const CREATE_SUCCESS_CATEGORY='CREATE_SUCCESS_CATEGORY'
export const CREATE_FAIL_CATEGORY='CREATE_FAIL_CATEGORY'

export const DELETE_REQUEST_CATEGORY='DELETE_REQUEST_CATEGORY'
export const DELETE_SUCCESS_CATEGORY='DELETE_SUCCESS_CATEGORY'
export const DELETE_FAIL_CATEGORY='DELETE_FAIL_CATEGORY'