export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAIL = "CREATE_ORDER_FAIL";

export const CREATE_ORDER_RESET = "CREATE_ORDER_RESET";

export const ORDER_REQUEST_DETAIL = "ORDER_REQUEST_DETAIL";
export const ORDER_SUCCESS_DETAIL = "ORDER_SUCCESS_DETAIL";
export const ORDER_FAIL_DETAIL = "ORDER_FAIL_DETAIL";

export const PAY_REQUEST_DETAIL = "PAY_REQUEST_DETAIL";
export const PAY_SUCCESS_DETAIL = "PAY_SUCCESS_DETAIL";
export const PAY_FAIL_DETAIL = "PAY_FAIL_DETAIL";
export const PAY_RESET_DETAIL = "PAY_RESET_DETAIL";

export const GET_REQUEST_MYORDERS = "GET_REQUEST_MYORDERS";
export const GET_SUCCESS_MYORDERS = "GET_SUCCESS_MYORDERS";
export const GET_FAIL_MYORDERS = "GET_FAIL_MYORDERS";
export const GET_RESET_MYORDERS = "GRESETEST_MYORDERS";

export const GET_REQUEST_ORDERS = "GET_REQUEST_ORDERS";
export const GET_SUCCESS_ORDERS = "GET_SUCCESS_ORDERS";
export const GET_FAIL_ORDERS = "GET_FAIL_ORDERS";
export const GET_RESET_ORDERS = "GRESETEST_ORDERS";

export const MARK_REQUEST_DELIVERED = "MARK_REQUEST_DELIVERED";
export const MARK_SUCCESS_DELIVERED = "MARK_SUCCESS_DELIVERED";
export const MARK_FAIL_DELIVERED = "MARK_FAIL_DELIVERED";
export const MARK_RESET_DELIVERED = "MARK_RESET_DELIVERED";

export const DELETE_ORDER_REQUEST = "DELETE_ORDER_REQUEST";
export const DELETE_ORDER_SUCCESS = "DELETE_ORDER_SUCCESS";
export const DELETE_ORDER_FAIL = "DELETE_ORDER_FAIL";