export const PRODUCTS_LIST_REQUEST='PRODUCTS_LIST_REQUEST'
export const PRODUCTS_LIST_SUCCESS='PRODUCTS_LIST_SUCCESS'
export const PRODUCTS_LIST_FAIL='PRODUCTS_LIST_FAIL'

export const PRODUCT_DETAIL_REQUEST='PRODUCT_DETAIL_REQUEST'
export const PRODUCT_DETAIL_SUCCESS='PRODUCT_DETAIL_SUCCESS'
export const PRODUCT_DETAIL_FAIL='PRODUCT_DETAIL_FAIL'
export const PRODUCT_DETAIL_RESET='PRODUCT_DETAIL_RESET'

export const PRODUCT_DELETE_REQUEST='PRODUCT_DELETE_REQUEST'
export const PRODUCT_DELETE_SUCCESS='PRODUCT_DELETE_SUCCESS'
export const PRODUCT_DELETE_FAIL='PRODUCTS_DELETE_FAIL'

export const CREATE_REGUEST_PRODUCT='CREATE_REGUEST_PRODUCT'
export const CREATE_SUCCESS_PRODUCT='CREATE_SUCCESS_PRODUCT'
export const CREATE_FAIL_PRODUCT='CREATE_FAIL_PRODUCT'
export const CREATE_RESET_PRODUCT='CREATE_RESET_PRODUCT'

export const UPDATE_REQUEST_PRODUCT='UPDATE_REQUEST_PRODUCT'
export const UPDATE_SUCCESS_PRODUCT='UPDATE_SUCCESS_PRODUCT'
export const UPDATE_FAIL_PRODUCT='UPDATE_FAIL_PRODUCT'
export const UPDATE_RESET_PRODUCT='UPDATE_RESET_PRODUCT'

export const CREATE_REGUEST_REVIEW='CREATE_REGUEST_REVIEW'
export const CREATE_SUCCESS_REVIEW='CREATE_SUCCESS_REVIEW'
export const CREATE_FAIL_REVIEW='CREATE_FAIL_REVIEW'

