export const USER_REQUEST_LOGIN='USER_REQUEST_LOGIN'
export const USER_SUCCESS_LOGIN='USER_SUCCESS_LOGIN'
export const USER_FAIL_LOGIN='USER_FAIL_LOGIN'

export const USER_LOGOUT='USER_LOGOUT'

export const USER_REQUEST_REGISTER='USER_REQUEST_REGISTER'
export const USER_SUCCESS_REGISTER='USER_SUCCESS_REGISTER'
export const USER_FAIL_REGISTER='USER_FAIL_REGISTER'

export const USER_DETAIL_REQUEST='USER_DETAIL_REQUEST'
export const USER_DETAIL_SUCCESS='USER_DETAIL_SUCCESS'
export const USER_DETAIL_FAIL='USER_DETAIL_FAIL'
export const USER_DETAIL_RESET='USER_DETAIL_RESET'

export const USER_REQUEST_UPDATE='USER_REQUEST_UPDATE'
export const USER_SUCCESS_UPDATE='USER_SUCCESS_UPDATE'
export const USER_FAIL_UPDATE='USER_FAIL_UPDATE'
export const USER_UPDATE_RESET='USER_UPDATE_RESET'

export const USERS_REQUEST_ADMIN='USERS_REQUEST_ADMIN'
export const USERS_SUCCESS_ADMIN='USERS_SUCCESS_ADMIN'
export const USERS_FAIL_ADMIN='USERS_FAIL_ADMIN'
export const USERS_RESET_ADMIN='USERS_RESET_ADMIN'

export const USER_DELETE_REQUEST_ADMIN='USER_DELETE_REQUEST_ADMIN'
export const USER_DELETE_SUCCESS_ADMIN='USER_DELETE_SUCCESS_ADMIN'
export const USER_DELETE_FAIL_ADMIN='USER_DELETE_FAIL_ADMIN'

export const USER_GETBYID_FAIL_ADMIN='USER_GETBYID_FAIL_ADMIN'
export const USER_GETBYID_SUCCESS_ADMIN='USER_GETBYID_SUCCESS_ADMIN'
export const USER_GETBYID_REQUEST_ADMIN='USER_GETBYID_REQUEST_ADMIN'

export const UPDATE_USER_REQUEST_ADMIN='UPDATE_USER_REQUEST_ADMIN'
export const UPDATE_USER_SUCCESS_ADMIN='UPDATE_USER_SUCCESS_ADMIN'
export const UPDATE_USER_FAIL_ADMIN='UPDATE_USER_FAIL_ADMIN'

