# Generated by Django 3.2.8 on 2021-10-31 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
