# Generated by Django 3.2.8 on 2021-10-31 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_product_category1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category1',
        ),
    ]
